# https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
spec:
  selector:
    matchLabels:
      app: freeipa
  serviceName: "freeipa"
  replicas: 1
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: freeipa
      automountServiceAccountToken: true
      containers:
      - image: quay.io/freeipa/freeipa-openshift-container:freeipa-server
        imagePullPolicy: IfNotPresent
        name: main
        # SYSTEMD_LOG_LEVEL=debug INIT_WRAPPER=1 DEBUG_TRACE=2 PASSWORD=Secret123 NAMESPACE=freeipa SYSTEMD_OFFLINE=1 podman run -it quay.io/freeipa/freeipa-openshift-container:freeipa-server no-exit ipa-server-install -U --realm APPS.MYKUBE.KARMALABS.COM --ca-subject="CN=freeipa-11111, O=APPS.MYKUBE.KARMALABS.COM" --no-ntp --no-sshd --no-ssh --verbose
        # podman run -it -e SYSTEMD_LOG_LEVEL=debug -e INIT_WRAPPER=1 -e DEBUG_TRACE=2 -e PASSWORD=Secret123 -e NAMESPACE=freeipa -e SYSTEMD_OFFLINE=1  quay.io/freeipa/freeipa-openshift-container:freeipa-server no-exit ipa-server-install -U --realm APPS.MYKUBE.KARMALABS.COM --ca-subject="CN=freeipa-11111, O=APPS.MYKUBE.KARMALABS.COM" --no-ntp --no-sshd --no-ssh --verbose
        command:
        - /usr/sbin/init
        args:
        - no-exit
        - ipa-server-install
        - -U
        # TODO Checkout this fields before deploy
        # TODO Define variable IPA_SERVER_REALM
        - --realm
        # - APPS.MYKUBE.KARMALABS.COM
        - $(IPA_SERVER_REALM)
        # TODO Define variable IPA_SERVER_CA_SUBJECT
        # - --ca-subject=CN=freeipa-SgD5xAV, O=APPS.MYKUBE.KARMALABS.COM
        - --ca-subject=$(IPA_SERVER_CA_SUBJECT)
        # TODO Define variable IPA_SERVER_DISABLE=ntp,sshd,ssh
        - --no-ntp
        - --no-sshd
        - --no-ssh
        - --verbose
        # envFrom:
        #   - name: IPA_SERVER_HOSTNAME
        #     configMapRef:
        #       name: config
              
        env:
        - name: KRB5_TRACE
          value: /dev/console
        - name: SYSTEMD_LOG_LEVEL
          value: debug
        - name: SYSTEMD_LOG_COLOR
          value: "no"
        - name: INIT_WRAPPER
          value: "1"
        - name: DEBUG_TRACE
          value: "2"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: IPA_SERVER_PASSWORD
              name: freeipa
              optional: false
        - name: NAMESPACE
          value: freeipa
        - name: IPA_SERVER_HOSTNAME
          value: $(IPA_SERVER_HOSTNAME)
        - name: container_uuid
          value: b01e51533bce49ce92b6bd4680edd46e
        - name: SYSTEMD_OFFLINE
          value: "1"
        - name: SYSTEMD_NSPAWN_API_VFS_WRITABLE
          value: network
        ports:
        - containerPort: 80
          name: http-tcp
          protocol: TCP
        - containerPort: 443
          name: https-tcp
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - CHOWN
            - FOWNER
            - DAC_OVERRIDE
            - SETUID
            - SETGID
            - KILL
            - NET_BIND_SERVICE
            - SETPCAP
            - SETFCAP
            - SYS_ADMIN
            - SYS_RESOURCE
            drop:
            - NET_RAW
            - SYS_CHROOT
            - FSETID
            - AUDIT_CONTROL
            - AUDIT_READ
            - BLOCK_SUSPEND
            - DAC_READ_SEARCH
            - IPC_LOCK
            - IPC_OWNER
            - LEASE
            - LINUX_IMMUTABLE
            - MAC_ADMIN
            - MAC_OVERRIDE
            - NET_ADMIN
            - NET_BROADCAST
            - SYS_BOOT
            - SYS_MODULE
            - SYS_NICE
            - SYS_PACCT
            - SYS_PTRACE
            - SYS_RAWIO
            - SYS_TIME
            - SYS_TTY_CONFIG
            - SYSLOG
            - WAKE_ALARM
            - SYS_RAWIO
            - MKNOD
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: systemd-tmp
        - mountPath: /var/run
          name: systemd-var-run
        - mountPath: /var/run/dirsrv
          name: systemd-var-dirsrv
      volumes:
      - name: data
        emptyDir: {}
      - emptyDir:
          medium: Memory
        name: systemd-var-run
      - emptyDir:
          medium: Memory
        name: systemd-var-dirsrv
      - emptyDir:
          medium: Memory
        name: systemd-run-rpcbind
      - emptyDir:
          medium: Memory
        name: systemd-tmp
